name: Build APK

on:
  push:
    branches: [ primary ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with: 
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      run: |
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        echo "sdk_root=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        
        echo "PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --info

    - uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
