name: Build APK

on:
  push:
    branches: [ primary ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Install Android Command Line Tools
      run: |
        mkdir -p $HOME/cmdline-tools
        cd $HOME/cmdline-tools
        curl -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip tools.zip
        sudo rm -rf $ANDROID_SDK_ROOT/cmdline-tools/latest
        sudo mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        sudo mv cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest
        echo "sdkmanager=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" >> $GITHUB_ENV

    - name: Install required SDK packages
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools" > /dev/null

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
